@uri= http://localhost:9000
@json=Content-Type: application/json
###查询所有标签
GET {{uri}}/label
###查询所有课程
GET {{uri}}/course/1/5

###查询某个分类下的所有课程
GET {{uri}}/course/subject/1/1/5

###查询某个课程
POST {{uri}}/course/parentId
{{json}}

{
    "parentId":"22"
}

###查询所有学科
GET {{uri}}/subject
###查询某个标签
GET {{uri}}/label/2
###添加标签
POST  {{uri}}/label
{{json}}

{
    "id": "6",
    "labelname": "ios6",
    "state": "1"
}
###修改标签
PUT   {{uri}}/label/5
{{json}}

{
    "id": "5",
    "labelname": "ios++",
    "state": "1"
}
###删除某个标签
DELETE   {{uri}}/label/2

###多条件查询标签
POST  {{uri}}/label/search
{{json}}

{
    "labelName": "H",
    "state": "1"
}

###分页查询标签
POST  {{uri}}/label/search/1/1
{{json}}

{
    "labelName": "H",
    "state": "1"
}

###用户登录
POST  {{uri}}/user/login
{{json}}

{
    "username":"yh",
    "password":"123"
}
###获取个人信息
GET {{uri}}/user/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDgxZjFiNzY5NTc4MjdmNGE2MjBmMyIsImlhdCI6MTU1NzY3MDM4OX0.jhj5xIVUnJOibuUFoXZyLhfSVRwCNHpGsNQmUYSkU3w
###获取个人订单信息
GET {{uri}}/user/orderinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDgxZjFiNzY5NTc4MjdmNGE2MjBmMyIsImlhdCI6MTU1NzY3MDM4OX0.jhj5xIVUnJOibuUFoXZyLhfSVRwCNHpGsNQmUYSkU3w
