@uri= http://localhost:9000
@json=Content-Type: application/json

###用户注册
POST    {{uri}}/user/register
{{json}}

{
  "username":"yh",
  "password":"123",
  "mobile": "18608212510",
  "nickname": "小明",
  "sex":"2"
}
###用户登录
POST    {{uri}}/user/login
{{json}}

{
  "username":"yh",
  "password":"123"
}

###添加管理员
POST    {{uri}}/admin
{{json}}

{
  "username": "yh",
  "password": "123",
  "state": "1"
}

###管理员登录
POST    {{uri}}/admin/login
{{json}}

{
  "username": "yh",
  "password": "123"
}

###管理员删除用户
DELETE    {{uri}}/user/1173053706409742336
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMTcyNzA5NTY5MjQ4NDk3NjY0Iiwic3ViIjoieWgiLCJpYXQiOjE1Njg1MTI0MTQsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE1Njg1MTYwMTR9.cEQvqOqcHLcCQGUTWUwreAVOw1mvFMdwEEQ6RG1Qbxg